# Generated by Django 3.1 on 2020-08-19 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='host',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='resources.host'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroup',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='resources.hostgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobgroup',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='resources.jobgroup'),
            preserve_default=False,
        ),
    ]
