# Generated by Django 3.1 on 2020-08-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200819_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.hostgroup'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.jobgroup'),
        ),
    ]
