# Generated by Django 3.1 on 2020-09-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200819_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
