# Generated by Django 3.1 on 2020-09-12 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0006_auto_20200911_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.host'),
        ),
        migrations.AlterField(
            model_name='job',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
