# Generated by Django 3.1 on 2020-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20200912_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='logs',
            field=models.CharField(max_length=10000),
        ),
    ]
