# Generated by Django 3.1 on 2020-09-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20200913_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='registered_by',
            new_name='created_by',
        ),
    ]
