# Generated by Django 3.1 on 2020-10-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20201006_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auth_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
