# Generated by Django 3.1 on 2020-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_auto_20201007_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('undefined', 'Undefined')], default='undefined', max_length=24),
        ),
    ]
