# Generated by Django 3.1 on 2020-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20201007_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('failure', 'Failure'), ('warning', 'Warning'), ('undefined', 'Undefined')], default='undefined', max_length=24),
        ),
    ]
