# Generated by Django 3.1 on 2020-12-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_auto_20201022_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('failure', 'Failure'), ('undefined', 'Undefined')], default='undefined', max_length=24),
        ),
    ]
